name: AWS Deployment via Azure AD OIDC

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Azure AD OIDC token
        id: get-azure-token
        run: |
          # Use curl to get token from Azure AD
          RESPONSE=$(curl -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -d "scope=https://graph.microsoft.com/.default" \
            -d "grant_type=client_credentials" \
            "https://login.microsoftonline.com/${{ secrets.AZURE_TENANT_ID }}/oauth2/v2.0/token")
          
          TOKEN=$(echo $RESPONSE | jq -r '.access_token')
          echo "token=${TOKEN}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ENTRA_ROLE }}
          aws-region: us-east-1
          web-identity-token-file: ${{ steps.get-azure-token.outputs.token }}
          role-session-name: github-actions-${{ github.run_id }}

      - name: Verify AWS credentials
        run: aws sts get-caller-identity
